project:
  type: website

website:
  title: "ISSS624 - Applied Geospatial Analytics"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: 1A - Geospatial Data Wrangling
            href: hands-on/hoe1.html
          - text: 1B - Choropleth Mapping
            href: hands-on/hoe1-choropleth.html
          - text: 2A - Spatial Weights and Application
            href: hands-on/hoe2-spatialweight.html
          - text: 2B - Global Measures of Spatial Autocorrelation
            href: hands-on/hoe2-globalautocor.html
          - text: 2C - Local Measures of Spatial Autocorrelation 
            href: hands-on/hoe2-localautocor.html
          - text: 3 - Flow Data 
            href: hands-on/hoe3.html
          - text: 4 - Geographically Weighted Regression (GWR)
            href: hands-on/hoe4.html
      - text: In-class Exercise
        menu:
          - text: 1 - Preparing The Data Flow
            href: in-class/ice1.html
          - text: 2 - sfdep for Spatial Weights, GLSA & EHSA
            href: in-class/ice2.html
          - text: 3 - Calibrating Spatial Interaction Models with R
            href: in-class/ice3.html
          - text: 4 - GDS and SIM with R
            href: in-class/ice4.html
      - text: Take-Home Exercise
        menu:
          - text: 1 - Geospatial Analytics for Public Goods
            href: take-home/the1.html
          - text: 2 - Applied Spatial Interaction Models (WIP)
            href: take-home/the2.html
    right:
      - href: index.qmd
        text: Home
      - icon: linkedin
        href: https://www.linkedin.com/in/muhamad-ameer-noor/
        aria-label: Linkedin
      - icon: book
        href: https://scholar.google.com/citations?user=TS_ilSMAAAAJ&hl=en&oi=ao
        aria-label: Google Scholar      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

