project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1, Wrangling
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1, Choropleth Mapping
            href: Hands-on_Ex1/Hands-on_Ex1-Choropleth.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

