project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1, Wrangling
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 1, Choropleth Mapping
            href: Hands-on_Ex1/Hands-on_Ex1-Choropleth.html
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1_demo.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

