project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1 - Wrangling
            href: hands-on/hoe1.html
          - text: Hands-on Exercise 1 - Choropleth Mapping
            href: hands-on/hoe1-choropleth.html
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: in-class/ice1.html
    right:
      - href: index.qmd
        text: Home
      - icon: linkedin
        href: https://www.linkedin.com/in/muhamad-ameer-noor/
        aria-label: Linkedin
      - icon: github
        href: https://github.com/ameernoor
        aria-label: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

